{
 "title": "New dashboard",
 "time": { "from": "1753-08-29T22:43:41.129Z", "to": "1753-08-30T20:43:41.129Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT tempout FROM weather LIMIT 50 "
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT windspeed FROM weather LIMIT 50 "
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT humidity FROM weather LIMIT 50 "
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT * FROM weather LIMIT 50 "
    }
   ]
  }
 ]
}